### ISSUE TITLE
Parsing of results stopped after 1st page

### ISSUE THREAD

**Issue by crombates** [ward/rust-chronorace#1]
When parsing the results for some chronorace url's only the results on the first page are used.
Example:
http://prod.chronorace.be/Classements/Classement.aspx?eventId=1187403838543924&lng=NL&mode=large&IdClassement=17321

**Comment by ward** [comment]
Sorry for the slow reply, missed the notification of this one. I will try to have a look at it this week.

**Comment by ward** [comment]
Should be fixed now, I originally only tested English pages and then added some extras to get Dutch pages working. Forgot to adjust it to also parse the subsequent pages. (To force chronorace to English, change the `lng=NL` to `lng=EN`)

It should be fixed now and work for both English and Dutch pages. (Perhaps I should just switch the language parameter on the program's end if it spots it, but oh well)

Thanks for the report, please let me know if you encounter any other issues!
